version: '3'
services:
  backend:
    restart: unless-stopped
    container_name: backend
    image: backend
    build: './backend'
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - database
  database:
    container_name: database
    image: database
    build: './database/'
    ports:
      - 27017:27017
    volumes:
      - ./database/data:/data/db
  frontend:
    restart: unless-stopped
    container_name: frontend
    image: frontend
    build: './frontend'
    volumes:
      - ./frontend/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - backend
  nginx:
    restart: unless-stopped
    container_name: nginx
    image: nginx
    build: './nginx'
    volumes:
      - ./nginx/nginx-conf:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
